### ISSUE TITLE
Typo dans la VF Terraform

### ISSUE THREAD

**Issue by kjbtech** [AntonyCanut/AntonyCanut#2]
J'ai découvert ces supers documentations via Linkedin, je me permets donc de te faire un retour sur la VF de Terraform.pdf.

La page 20 et 21 semble être complètement identique, à l'exception de la petite image en haut à droite du PDF.

**Comment by AntonyCanut** [comment]
Aie ! 
Merci pour ce retour, j'ai fait le fix :)
